spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rds-admin
    username: postgres
    password: totvs@123

  flyway:
    schemas: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:      
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/spring-projects/spring-boot/issues/12007
        hbm2ddl:
          auto: "none"
        show_sql: true
        format_sql: true

  cloud:
    stream:
      default-binder: rabbit1
      bindings:
        rds-input-events:       
          destination: rds-input-events
          group: requests
        rds-output-events:
          destination: rds-input-events
        tjf-messaging-error-input:
          destination: rds-errors
          group: errors
        tjf-messaging-error-output:
          destination: rds-errors
          group: errors
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

server:
  port: 8888